language: node_js
node_js:
- node
- '8'
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH=$HOME/.yarn/bin:$PATH
- export BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
- yarn global add greenkeeper-lockfile@1
- yarn global add coveralls
- yarn global add codecov
cache: false
install:
- |
  if [[ $BRANCH == "greenkeeper/"* ]]; then
    echo Greenkeeper build; yarn install;
  else
    echo Normal build - frozen lockfile; yarn install --frozen-lockfile;
  fi
before_script: greenkeeper-lockfile-update
script:
- yarn test
- cat ./coverage/lcov.info | coveralls
- codecov -f coverage/coverage-final.json
after_script: greenkeeper-lockfile-upload
stages:
- name: test
- name: deploy
  if: tag =~ ^v AND fork = false AND type = push
jobs:
  include:
  - stage: test
    if: type = cron
    node_js: '8'
    os: osx
    osx_image: xcode9.2
  - stage: test
    if: type = cron
    node_js: '7'
  - stage: test
    if: type = cron
    node_js: '6'
  - stage: test
    if: type = cron
    node_js: '5'
  - stage: test
    if: type = cron OR tag =~ ^v
    node_js: '4'
  - stage: deploy
    before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
    - export PATH=$HOME/.yarn/bin:$PATH
    install: []
    before_script: []
    script:
      - yarn install --frozen-lockfile
      - yarn test
      - tarn tidy-ci
    after_script: []
    deploy:
      provider: npm
      email: github-external-bot@holvonix.com
      skip_cleanup: true
      api_key: "$NPM_API_KEY"
      on:
        tags: true
